// ─── Application / Hub state ────────────────────────────────────────────────

export type ConnectionWatchdogState = {
  isAttemptingConnection?: boolean;
  isAwaitingVpn?: boolean;
  isEnabled?: boolean;
  nextAttemptAt?: string | null;
};

export type DistributedNetworkState = {
  branchLevel?: number;
  branchRoot?: string | null;
  canAcceptChildren?: boolean;
  childLimit?: number;
  children?: string[];
  hasBranchRoot?: boolean;
  hasParent?: boolean;
  isBranchRoot?: boolean;
  parent?: string | null;
};

export type HealthState = {
  search?: {
    incoming?: {
      dropRate?: number;
      latency?: number;
      queueDepth?: number;
    };
  };
};

export type RelayControllerState = {
  address?: string | null;
  state?: 'Connected' | 'Connecting' | 'Reconnecting' | 'Disconnected';
};

export type RelayState = {
  agents?: unknown[];
  controller?: RelayControllerState;
  mode?: 'Controller' | 'Agent';
};

export type ServerState = {
  address?: string | null;
  isConnected?: boolean;
  isConnecting?: boolean;
  isLoggedIn?: boolean;
  isLoggingIn?: boolean;
  isTransitioning?: boolean;
};

export type ShareState = {
  cancelled?: boolean;
  directories?: number;
  faulted?: boolean;
  files?: number;
  hosts?: string[];
  ready?: boolean;
  scanPending?: boolean;
  scanProgress?: number;
  scanning?: boolean;
};

export type UserState = {
  privileges?: {
    isPrivileged?: boolean;
    privilegesRemaining?: number;
  };
  statistics?: {
    averageSpeed?: number;
    directoryCount?: number;
    fileCount?: number;
    uploadCount?: number;
  };
  username?: string | null;
};

export type VersionState = {
  current?: string;
  full?: string;
  isCanary?: boolean;
  isDevelopment?: boolean;
  isUpdateAvailable?: boolean | null;
  latest?: string | null;
};

export type VpnState = {
  forwardedPort?: number | null;
  isConnected?: boolean;
  isReady?: boolean;
  location?: string | null;
  publicIPAddress?: string | null;
};

export type ApplicationState = {
  connectionWatchdog?: ConnectionWatchdogState;
  distributedNetwork?: DistributedNetworkState;
  health?: HealthState;
  pendingReconnect?: boolean;
  pendingRestart?: boolean;
  relay?: RelayState;
  rooms?: string[];
  server?: ServerState;
  shares?: ShareState;
  user?: UserState;
  users?: unknown[];
  version?: VersionState;
  vpn?: VpnState;
};

export type AppContextValue = {
  options: ApplicationOptions;
  state: ApplicationState;
};

// ─── Application Options ─────────────────────────────────────────────────────
// Mirrors the C# Options class (src/slskd/Core/Options.cs).
// NOTE: This type was largely generated by an LLM verify field names and
// nullability against Options.cs before trusting any specific field.
// Secret fields are redacted to "*****" by the server before being sent.

type SecretString = string;

export type ApplicationOptions = {
  appDirectory?: string;
  blacklist?: BlacklistOptions;
  configurationFile?: string;
  debug?: boolean;
  directories?: DirectoriesOptions;
  feature?: FeatureOptions;
  filters?: FiltersOptions;
  flags?: FlagsOptions;
  generateCertificate?: boolean;
  generateSecret?: boolean;
  headless?: boolean;
  instanceName?: string;
  integrations?: IntegrationsOptions;
  logger?: LoggerOptions;
  metrics?: MetricsOptions;
  permissions?: PermissionsOptions;
  relay?: RelayOptions;
  remoteConfiguration?: boolean;
  remoteFileManagement?: boolean;
  retention?: RetentionOptions;
  rooms?: string[];
  shares?: SharesOptions;
  showEnvironmentVariables?: boolean;
  showHelp?: boolean;
  showVersion?: boolean;
  soulseek?: SoulseekOptions;
  throttling?: ThrottlingOptions;
  transfers?: TransfersOptions;
  web?: WebOptions;
};

type FlagsOptions = {
  caseSensitiveRegEx?: boolean;
  experimental?: boolean;
  forceMigrations?: boolean;
  forceShareScan?: boolean;
  legacyWindowsTcpKeepalive?: boolean;
  logSQL?: boolean;
  logUnobservedExceptions?: boolean;
  noConfigWatch?: boolean;
  noConnect?: boolean;
  noLogo?: boolean;
  noShareScan?: boolean;
  noSqlitePooling?: boolean;
  noStart?: boolean;
  noVersionCheck?: boolean;
  optimisticRelayFileInfo?: boolean;
  volatile?: boolean;
};

type RelayOptions = {
  agents?: Record<string, RelayAgentConfigurationOptions>;
  controller?: RelayControllerConfigurationOptions;
  enabled?: boolean;
  mode?: string;
};

type RelayControllerConfigurationOptions = {
  address?: string;
  apiKey?: SecretString;
  downloads?: boolean;
  ignoreCertificateErrors?: boolean;
  secret?: SecretString;
};

type RelayAgentConfigurationOptions = {
  cidr?: string;
  instanceName?: SecretString;
  secret?: SecretString;
};

type PermissionsOptions = {
  file?: { mode?: string };
};

type DirectoriesOptions = {
  downloads?: string;
  incomplete?: string;
};

type SharesOptions = {
  cache?: ShareCacheOptions;
  directories?: string[];
  filters?: string[];
};

type ShareCacheOptions = {
  retention?: number | null;
  storageMode?: string;
  workers?: number;
};

type TransfersOptions = {
  download?: GlobalDownloadOptions;
  groups?: GroupsOptions;
  upload?: GlobalUploadOptions;
};

type GlobalUploadOptions = {
  limits?: LimitsOptions;
  slots?: number;
  speedLimit?: number;
};

type GlobalDownloadOptions = {
  retry?: DownloadRetryOptions;
  slots?: number;
  speedLimit?: number;
};

type DownloadRetryOptions = {
  attempts?: number;
  delay?: number;
  maxDelay?: number;
  partial?: string;
};

type LimitsOptions = {
  daily?: Limits;
  queued?: Limits;
  weekly?: Limits;
};

type Limits = {
  failures?: number | null;
  files?: number | null;
  megabytes?: number | null;
};

type GroupsOptions = {
  blacklisted?: BlacklistedGroupOptions;
  default?: BaseGroupOptions;
  leechers?: LeecherOptions;
  userDefined?: Record<string, UserDefinedGroupOptions>;
};

type GroupUploadOptions = {
  limits?: LimitsOptions;
  priority?: number;
  slots?: number;
  speedLimit?: number;
  strategy?: string;
};

type BaseGroupOptions = {
  upload?: GroupUploadOptions;
};

type LeecherOptions = BaseGroupOptions & {
  thresholds?: { directories?: number; files?: number };
};

type BlacklistedGroupOptions = {
  cidrs?: string[];
  members?: string[];
  patterns?: string[];
};

type UserDefinedGroupOptions = BaseGroupOptions & {
  members?: string[];
};

type BlacklistOptions = {
  enabled?: boolean;
  file?: string;
};

type FiltersOptions = {
  search?: { request?: string[] };
};

type WebOptions = {
  authentication?: WebAuthenticationOptions;
  contentPath?: string;
  https?: HttpsOptions;
  ipAddress?: string;
  logging?: boolean;
  port?: number;
  socket?: string;
  urlBase?: string;
};

type HttpsOptions = {
  certificate?: { password?: SecretString; pfx?: string };
  disabled?: boolean;
  force?: boolean;
  ipAddress?: string;
  port?: number;
};

type WebAuthenticationOptions = {
  apiKey?: SecretString;
  apiKeys?: Record<
    string,
    { cidr?: string; key?: SecretString; role?: string }
  >;
  disabled?: boolean;
  jwt?: { key?: SecretString; ttl?: number };
  password?: SecretString;
  username?: string;
};

type RetentionOptions = {
  files?: { complete?: number | null; incomplete?: number | null };
  logs?: number;
  search?: number | null;
  transfers?: {
    download?: TransferTypeRetentionOptions;
    upload?: TransferTypeRetentionOptions;
  };
};

type TransferTypeRetentionOptions = {
  cancelled?: number | null;
  errored?: number | null;
  failed?: number | null;
  succeeded?: number | null;
};

type ThrottlingOptions = {
  search?: {
    incoming?: {
      circuitBreaker?: number;
      concurrency?: number;
      responseFileLimit?: number;
    };
  };
};

type LoggerOptions = {
  disk?: boolean;
  loki?: string;
  noColor?: boolean;
};

type MetricsOptions = {
  authentication?: {
    disabled?: boolean;
    password?: SecretString;
    username?: string;
  };
  enabled?: boolean;
  url?: string;
};

type FeatureOptions = {
  swagger?: boolean;
};

type SoulseekOptions = {
  address?: string;
  connection?: {
    buffer?: {
      read?: number;
      transfer?: number;
      write?: number;
      writeQueue?: number;
    };
    proxy?: {
      address?: string;
      enabled?: boolean;
      password?: SecretString;
      port?: number | null;
      username?: string;
    };
    timeout?: { connect?: number; inactivity?: number; transfer?: number };
  };
  description?: string;
  diagnosticLevel?: string;
  distributedNetwork?: {
    childLimit?: number;
    disableChildren?: boolean;
    disabled?: boolean;
    logging?: boolean;
  };
  listenIpAddress?: string;
  listenPort?: number;
  password?: SecretString;
  picture?: string;
  port?: number;
  username?: string;
};

type IntegrationsOptions = {
  ftp?: {
    address?: string;
    connectionTimeout?: number;
    enabled?: boolean;
    encryptionMode?: string;
    ignoreCertificateErrors?: boolean;
    overwriteExisting?: boolean;
    password?: SecretString;
    port?: number;
    remotePath?: string;
    retryAttempts?: number;
    username?: string;
  };
  pushbullet?: {
    accessToken?: SecretString;
    cooldownTime?: number;
    enabled?: boolean;
    notificationPrefix?: string;
    notifyOnPrivateMessage?: boolean;
    notifyOnRoomMention?: boolean;
    retryAttempts?: number;
  };
  scripts?: Record<
    string,
    {
      on?: string[];
      run?: {
        arglist?: string[];
        args?: string;
        command?: string;
        executable?: string;
      };
    }
  >;
  vpn?: {
    enabled?: boolean;
    gluetun?: {
      apiKey?: SecretString;
      password?: SecretString;
      pollingInterval?: number;
      timeout?: number;
      url?: string;
      username?: string;
      version?: number;
    };
    pollingInterval?: number;
    portForwarding?: boolean;
  };
  webhooks?: Record<
    string,
    {
      call?: {
        headers?: Array<{ name?: string; value?: string }>;
        ignoreCertificateErrors?: boolean;
        url?: string;
      };
      on?: string[];
      retry?: { attempts?: number };
      timeout?: number;
    }
  >;
};

// ─── Transfers ───────────────────────────────────────────────────────────────

export type TransferDirection = 'Upload' | 'Download';

// State is a C# flags enum serialized as a comma-separated string,
// e.g. "Queued, Locally" or "Completed, Succeeded".
export type TransferState =
  | 'None'
  | 'Requested'
  | 'Queued'
  | 'Queued, Locally'
  | 'Queued, Remotely'
  | 'Initializing'
  | 'InProgress'
  | 'Completed, Succeeded'
  | 'Completed, Cancelled'
  | 'Completed, TimedOut'
  | 'Completed, Errored'
  | 'Completed, Rejected'
  | 'Completed, Aborted'
  | (string & {}); // allow unknown combinations without losing autocomplete

export type TransferFile = {
  attempts: number;
  averageSpeed: number;
  batchId: string | null;
  // computed server-side
  bytesRemaining: number;
  bytesTransferred: number;
  direction: TransferDirection;
  elapsedTime: string | null;
  endedAt: string | null;
  enqueuedAt: string | null;
  exception: string | null;
  filename: string;
  id: string;
  nextAttemptAt: string | null;
  percentComplete: number;
  placeInQueue: number | null;
  remainingTime: string | null;
  removed: boolean;
  requestedAt: string;
  size: number;
  startedAt: string | null;
  state: TransferState;
  username: string;
};

export type TransferDirectory = {
  directory: string;
  fileCount: number;
  files: TransferFile[];
};

export type TransferUser = {
  directories: TransferDirectory[];
  username: string;
};
